# Generated by Django 4.2 on 2025-06-08 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_payment_transaction_id_payment_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xppackage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='xppackage',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='xppackage',
            name='name',
        ),
    ]
