# Generated by Django 4.2 on 2025-06-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_xppackage_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xppackage',
            options={'ordering': ['price_in_naira']},
        ),
        migrations.RenameField(
            model_name='xppackage',
            old_name='price',
            new_name='price_in_naira',
        ),
        migrations.AddField(
            model_name='xppackage',
            name='price_in_usdt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
