# Generated by Django 4.2 on 2025-06-06 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositcryptoreceipt',
            name='exchange',
            field=models.ForeignKey(help_text='The exchange platform used for the transaction', on_delete=django.db.models.deletion.CASCADE, to='receipts.exchangereceipttemplate'),
        ),
        migrations.AlterField(
            model_name='exchangereceipttemplate',
            name='type',
            field=models.CharField(choices=[('binance', 'Binance'), ('coinbase', 'Coinbase')], max_length=20),
        ),
    ]
