# Generated by Django 4.2 on 2025-06-07 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_alter_depositcryptoreceipt_exchange_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditbankreceipt',
            old_name='beneficiary_account_number',
            new_name='your_account_number',
        ),
        migrations.RenameField(
            model_name='creditbankreceipt',
            old_name='beneficiary_bank',
            new_name='your_bank',
        ),
        migrations.RenameField(
            model_name='creditbankreceipt',
            old_name='beneficiary_name',
            new_name='your_name',
        ),
        migrations.RenameField(
            model_name='debitbankreceipt',
            old_name='sender_account_number',
            new_name='your_account_number',
        ),
        migrations.RenameField(
            model_name='debitbankreceipt',
            old_name='sender_bank',
            new_name='your_bank',
        ),
        migrations.RenameField(
            model_name='debitbankreceipt',
            old_name='sender_name',
            new_name='your_name',
        ),
    ]
