# Generated by Django 4.2 on 2025-06-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_rename_beneficiary_account_number_creditbankreceipt_your_account_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankreceipttemplate',
            options={'verbose_name': 'Bank Template', 'verbose_name_plural': 'Bank Templates'},
        ),
        migrations.AlterField(
            model_name='bankreceipttemplate',
            name='type',
            field=models.CharField(choices=[('first_bank', 'First Bank of Nigeria'), ('chase_bank', 'Chase Bank'), ('paypal', 'PayPal'), ('transfer_wise', 'Transfer Wise'), ('access_bank', 'Access Bank'), ('google_pay', 'Google Pay'), ('banco_popular', 'Banco Popular'), ('iptu', 'IPTU'), ('bank_of_america', 'Bank of America')], max_length=20),
        ),
    ]
