# Generated by Django 4.2 on 2025-06-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0004_alter_bankreceipttemplate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditbankreceipt',
            name='sender_account_number',
            field=models.CharField(blank=True, help_text='Please type in the correct account number in full', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='creditbankreceipt',
            name='your_account_number',
            field=models.CharField(blank=True, help_text='Please type in your account number in full', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='debitbankreceipt',
            name='beneficiary_account_number',
            field=models.CharField(blank=True, help_text='Please type in the correct account number in full', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='debitbankreceipt',
            name='your_account_number',
            field=models.CharField(blank=True, help_text='Please type in the correct account number in full', max_length=10, null=True),
        ),
    ]
